export {createApp} from './app'
export {h} from './h'
export {renderSlots} from './slot'
export {createTextVNode} from './vnode'
export {getCurrentInstance} from './setupComponent'
export {inject} from './api/inject'
export {provide} from './api/provide'